import type { OwnerChannel } from "@domo/owner-services";

export const ownerLabels = {
  "approval:get": "Consultar um pedido de acesso",
  "approval:ready": "Preparar a revisão de acesso",
  "approval:decide": "Confirmar a decisão de acesso",
  "audit:page": "Consultar o histórico",
  "audit:activity": "Consultar uma atividade",
  "audit:clear": "Apagar o histórico",
  "approvals:pending": "Consultar pedidos pendentes",
  "rules:list": "Consultar concessões permanentes",
  "rules:remove": "Revogar uma concessão permanente",
  "gatekeeperRecovery:get": "Consultar uma recusa do revisor",
  "gatekeeperRecovery:dismiss": "Dispensar o aviso de recusa",
  "gatekeeperRecovery:suggest": "Revisar as instruções após uma recusa",
  "ui:getTab": "Consultar a seção preferida",
  "ui:setTab": "Guardar a seção preferida",
  "settings:getRelay": "Consultar a conexão com a Plow",
  "settings:signOut": "Sair da conta Plow",
  "onboarding:open": "Abrir o primeiro acesso",
  "external:open": "Abrir uma página de suporte ou conta",
  "connect:get": "Consultar agentes conectados",
  "cloud:refresh": "Atualizar agentes na nuvem",
  "cloud:agents": "Consultar agentes na nuvem",
  "connect:create": "Conectar um agente",
  "cloud:remove": "Remover um agente na nuvem",
  "cloud:newAgentMessages": "Conectar um agente por mensagem",
  "cloud:awaitNewAgent": "Acompanhar a conexão de um agente",
  "cloud:changeLine": "Alterar a linha de um agente",
  "cloud:openMessages": "Abrir mensagens de um agente",
  "roster:remove": "Remover um agente conectado",
  "connect:dismiss": "Fechar os dados de conexão",
  "onboarding:get": "Consultar o primeiro acesso",
  "onboarding:begin": "Iniciar o primeiro acesso",
  "onboarding:advance": "Avançar no primeiro acesso",
  "onboarding:back": "Voltar no primeiro acesso",
  "onboarding:setTelemetry": "Alterar dados de diagnóstico no primeiro acesso",
  "onboarding:newCode": "Solicitar outro código de acesso",
  "onboarding:gatekeeperPresets": "Consultar exemplos de instruções",
  "onboarding:gatekeeperPreview": "Experimentar as instruções do Gatekeeper",
  "onboarding:openMessages": "Abrir a mensagem de ativação",
  "onboarding:finish": "Concluir o primeiro acesso",
  "connectors:refresh": "Atualizar contas conectadas",
  "connectors:connect": "Conectar uma conta Google",
  "connectors:disconnect": "Desconectar uma conta Google",
  "connectors:setDefault": "Escolher a conta Google padrão",
  "settings:setApprovalMode": "Alterar o modo do Gatekeeper",
  "settings:getAgentPurpose": "Consultar instruções do Gatekeeper",
  "settings:setAgentPurpose": "Salvar instruções do Gatekeeper",
  "settings:getInference": "Consultar o estado do revisor",
  "vault:items": "Consultar itens do cofre",
  "vault:search": "Buscar no cofre",
  "vault:item": "Consultar um item do cofre",
  "vault:reveal": "Revelar um campo protegido",
  "vault:totp": "Consultar um código de autenticação",
  "vault:deleteItem": "Remover um item do cofre",
  "vault:saveItem": "Guardar um item no cofre",
  "vault:importSources": "Consultar fontes de importação",
  "vault:importInspect": "Revisar uma importação de senhas",
  "vault:importFile": "Escolher um arquivo de senhas",
  "vault:importPick": "Escolher os cofres a importar",
  "vault:importCommit": "Confirmar a importação de senhas",
  "vault:importCancel": "Cancelar a importação de senhas",
  "vault:exchangePending": "Revisar o uso de uma credencial",
  "viewer:state": "Acompanhar o navegador privado",
  "status:get": "Consultar o estado do computador",
  "capabilities:get": "Consultar permissões do computador",
  "capabilities:act": "Solicitar uma permissão",
  "capabilities:dismiss": "Dispensar um aviso de permissão",
  "capabilities:bannerSeen": "Marcar o aviso de permissão como visto",
  "plugins:get": "Consultar ferramentas do Latch",
  "plugins:acknowledge": "Confirmar as permissões das ferramentas",
  "plugins:setEnabled": "Ativar ou desativar uma ferramenta",
  "requirements:act": "Concluir o acesso de uma ferramenta",
  "app:relaunch": "Reiniciar o serviço do Latch",
  "grant:state": "Consultar uma solicitação de permissão",
  "fullDisk:dragInfo": "Preparar o acesso completo ao disco",
  "fullDisk:tileImage": "Mostrar a identidade do Latch nas permissões",
  "fullDisk:dragStart": "Adicionar o Latch às permissões do macOS",
  "fullDisk:panelHold": "Manter aberta a revisão de permissões",
  "fullDisk:panelHeight": "Ajustar a revisão de permissões",
  "fullDisk:dismiss": "Fechar a revisão de permissões",
  "launch:get": "Consultar a inicialização automática",
  "launch:set": "Alterar a inicialização automática",
  "updates:get": "Consultar atualizações do Latch",
  "updates:check": "Buscar atualizações do Latch",
  "updates:restart": "Reiniciar para aplicar uma atualização",
  "updates:dismiss": "Dispensar o aviso de atualização",
  "updates:setAutoCheck": "Alterar a busca automática de atualizações",
  "updates:setAutoInstall": "Alterar a instalação automática de atualizações",
  "power:getKeepAwake": "Consultar a disponibilidade do computador",
  "power:setKeepAwake": "Manter o computador disponível",
  "telemetry:get": "Consultar dados de diagnóstico",
  "telemetry:set": "Alterar dados de diagnóstico",
  "ui:confirmLeaveReply": "Confirmar a saída de uma etapa",
} satisfies Record<OwnerChannel, string>;

export const ownerReasons = {
  owner_not_enrolled: "Conecte um canal de proprietário verificado.",
  plow_backend_adapter_required: "Conecte o serviço autorizado da Plow.",
  plow_sign_in_required: "Entre na sua conta Plow.",
  protected_secret_codec_required: "Conecte um armazenamento protegido de credenciais.",
  secret_store_locked: "Desbloqueie o armazenamento protegido.",
  protected_owner_surface_required: "Este dado exige uma superfície privada do proprietário.",
  protected_owner_input_required: "Este pedido exige entrada privada de credenciais.",
  protected_native_vault_adapter_required: "Conecte o cofre nativo protegido.",
  protected_credential_exchange_adapter_required: "Conecte o fluxo protegido de uso de credenciais.",
  signed_native_host_adapter_required: "Instale a integração assinada com o macOS.",
  signed_native_host_events_required: "Conecte os eventos da integração assinada.",
  staged_browser_runtime_required: "Instale o navegador privado do Latch.",
  native_link_opener_required: "Conecte a abertura de links no computador.",
  native_file_picker_required: "Conecte a seleção privada de arquivos.",
  native_import_sources_adapter_required: "Conecte as fontes nativas de importação.",
  host_presentation_adapter_required: "Conecte esta etapa à interface do host.",
  host_presentation_events_required: "Conecte os eventos da interface do host.",
  plow_reviewer_adapter_required: "Conecte o revisor autorizado da Plow.",
  owner_controller_command_required: "Use a revisão de acesso do proprietário.",
  owner_action_in_progress: "Aguarde o pedido de proprietário em andamento.",
};
