import { z } from "zod";

export const OWNER_CHANNELS = [
  "approval:get",
  "approval:ready",
  "approval:decide",
  "audit:page",
  "audit:activity",
  "audit:clear",
  "approvals:pending",
  "rules:list",
  "rules:remove",
  "gatekeeperRecovery:get",
  "gatekeeperRecovery:dismiss",
  "gatekeeperRecovery:suggest",
  "ui:getTab",
  "ui:setTab",
  "settings:getRelay",
  "settings:signOut",
  "onboarding:open",
  "external:open",
  "connect:get",
  "cloud:refresh",
  "cloud:agents",
  "connect:create",
  "cloud:remove",
  "cloud:newAgentMessages",
  "cloud:awaitNewAgent",
  "cloud:changeLine",
  "cloud:openMessages",
  "roster:remove",
  "connect:dismiss",
  "onboarding:get",
  "onboarding:begin",
  "onboarding:advance",
  "onboarding:back",
  "onboarding:setTelemetry",
  "onboarding:newCode",
  "onboarding:gatekeeperPresets",
  "onboarding:gatekeeperPreview",
  "onboarding:openMessages",
  "onboarding:finish",
  "connectors:refresh",
  "connectors:connect",
  "connectors:disconnect",
  "connectors:setDefault",
  "settings:setApprovalMode",
  "settings:getAgentPurpose",
  "settings:setAgentPurpose",
  "settings:getInference",
  "vault:items",
  "vault:search",
  "vault:item",
  "vault:reveal",
  "vault:totp",
  "vault:deleteItem",
  "vault:saveItem",
  "vault:importSources",
  "vault:importInspect",
  "vault:importFile",
  "vault:importPick",
  "vault:importCommit",
  "vault:importCancel",
  "vault:exchangePending",
  "viewer:state",
  "status:get",
  "capabilities:get",
  "capabilities:act",
  "capabilities:dismiss",
  "capabilities:bannerSeen",
  "plugins:get",
  "plugins:acknowledge",
  "plugins:setEnabled",
  "requirements:act",
  "app:relaunch",
  "grant:state",
  "fullDisk:dragInfo",
  "fullDisk:tileImage",
  "fullDisk:dragStart",
  "fullDisk:panelHold",
  "fullDisk:panelHeight",
  "fullDisk:dismiss",
  "launch:get",
  "launch:set",
  "updates:get",
  "updates:check",
  "updates:restart",
  "updates:dismiss",
  "updates:setAutoCheck",
  "updates:setAutoInstall",
  "power:getKeepAwake",
  "power:setKeepAwake",
  "telemetry:get",
  "telemetry:set",
  "ui:confirmLeaveReply",
] as const;

export const OWNER_EVENTS = [
  "rules:changed",
  "gatekeeperRecovery:changed",
  "vault:exchange",
  "ui:showCapabilities",
  "ui:showAuditBlocked",
  "ui:showGatekeeperRecovery",
  "fullDisk:dragEnd",
  "audit:changed",
  "capabilities:changed",
  "status:changed",
  "updates:changed",
  "ui:showSettings",
  "ui:confirmLeave",
  "onboarding:changed",
  "connectors:changed",
  "connect:changed",
  "approval:suggestion",
] as const;

export const ownerChannelSchema = z.enum(OWNER_CHANNELS);
export type OwnerChannel = z.infer<typeof ownerChannelSchema>;
export type OwnerEventChannel = (typeof OWNER_EVENTS)[number];

export const SOURCE_FAMILIES = {
  "approval:get": "policy",
  "approval:ready": "policy",
  "approval:decide": "policy",
  "audit:page": "audit",
  "audit:activity": "audit",
  "audit:clear": "audit",
  "approvals:pending": "policy",
  "rules:list": "policy",
  "rules:remove": "policy",
  "gatekeeperRecovery:get": "policy",
  "gatekeeperRecovery:dismiss": "policy",
  "gatekeeperRecovery:suggest": "policy",
  "ui:getTab": "desktop_shell",
  "ui:setTab": "desktop_shell",
  "settings:getRelay": "owner_settings",
  "settings:signOut": "owner_settings",
  "onboarding:open": "onboarding",
  "external:open": "native_launch",
  "connect:get": "agent_management",
  "cloud:refresh": "agent_management",
  "cloud:agents": "agent_management",
  "connect:create": "agent_management",
  "cloud:remove": "agent_management",
  "cloud:newAgentMessages": "agent_management",
  "cloud:awaitNewAgent": "agent_management",
  "cloud:changeLine": "agent_management",
  "cloud:openMessages": "agent_management",
  "roster:remove": "agent_management",
  "connect:dismiss": "agent_management",
  "onboarding:get": "onboarding",
  "onboarding:begin": "onboarding",
  "onboarding:advance": "onboarding",
  "onboarding:back": "onboarding",
  "onboarding:setTelemetry": "onboarding",
  "onboarding:newCode": "onboarding",
  "onboarding:gatekeeperPresets": "onboarding",
  "onboarding:gatekeeperPreview": "onboarding",
  "onboarding:openMessages": "onboarding",
  "onboarding:finish": "onboarding",
  "connectors:refresh": "connected_accounts",
  "connectors:connect": "connected_accounts",
  "connectors:disconnect": "connected_accounts",
  "connectors:setDefault": "connected_accounts",
  "settings:setApprovalMode": "owner_settings",
  "settings:getAgentPurpose": "owner_settings",
  "settings:setAgentPurpose": "owner_settings",
  "settings:getInference": "owner_settings",
  "vault:items": "vault",
  "vault:search": "vault",
  "vault:item": "vault",
  "vault:reveal": "vault",
  "vault:totp": "vault",
  "vault:deleteItem": "vault",
  "vault:saveItem": "vault",
  "vault:importSources": "vault",
  "vault:importInspect": "vault",
  "vault:importFile": "vault",
  "vault:importPick": "vault",
  "vault:importCommit": "vault",
  "vault:importCancel": "vault",
  "vault:exchangePending": "vault",
  "viewer:state": "browser_owner_view",
  "status:get": "status",
  "capabilities:get": "permissions",
  "capabilities:act": "permissions",
  "capabilities:dismiss": "permissions",
  "capabilities:bannerSeen": "permissions",
  "plugins:get": "plugins",
  "plugins:acknowledge": "plugins",
  "plugins:setEnabled": "plugins",
  "requirements:act": "permissions",
  "app:relaunch": "lifecycle",
  "grant:state": "permissions",
  "fullDisk:dragInfo": "native_permission_panel",
  "fullDisk:tileImage": "native_permission_panel",
  "fullDisk:dragStart": "native_permission_panel",
  "fullDisk:panelHold": "native_permission_panel",
  "fullDisk:panelHeight": "native_permission_panel",
  "fullDisk:dismiss": "native_permission_panel",
  "launch:get": "availability",
  "launch:set": "availability",
  "updates:get": "updates",
  "updates:check": "updates",
  "updates:restart": "updates",
  "updates:dismiss": "updates",
  "updates:setAutoCheck": "updates",
  "updates:setAutoInstall": "updates",
  "power:getKeepAwake": "availability",
  "power:setKeepAwake": "availability",
  "telemetry:get": "telemetry",
  "telemetry:set": "telemetry",
  "ui:confirmLeaveReply": "desktop_shell",
} satisfies Record<OwnerChannel, string>;
